### ISSUE TITLE
Package cannot be found on packagist.org

### ISSUE THREAD

**Issue by webong** [Flutterwave/Flutterwave-Rave-PHP-SDK#16]
I am unable to make use of this SDK, in which I can't install via composer.

**Comment by JayNatti** [comment]
Please  did you get a solution. Encountering same isshe

**Comment by webong** [comment]
I didn't get any response @JayNatti ...

**Comment by peter279k** [comment]
It's available [here](https://packagist.org/packages/flutterwavedev/flutterwave-php)...
