### ISSUE TITLE
FLutterWave explicit verion contraints 

### ISSUE THREAD

**Issue by jecordjotse** [Flutterwave/Flutterwave-Rave-PHP-SDK#19]
I keep getting this error ' Could not find a version of package flutterwave/flutterwave-php matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.'

**Comment by Corvus97** [comment]
Hello @jecordjotse, 

Thanks for bringing this to our attention.

Kindly send the steps we can use to replicate this error at our end in a mail to hi@flutterwavego.com.

We look forward to hearing from you soon.

Remain Awesome,
Cornelius.
