### ISSUE TITLE
Page not directing well.

### ISSUE THREAD

**Issue by UOPIUS** [Flutterwave/Flutterwave-Rave-PHP-SDK#3]
Am a newbie and have never integrated a payment system before. I don't understand why this http://hosted.flutterwave.com/processPayment.php is present in the first line in the paymentForm.php inside the form element.

**Comment by Corvus97** [comment]
Hello @UOPIUS ,

Apologies for the late response.

The processPayment.php file is needed to handle the logic for the payment form.

You can reach out to our developers for further assistance. Shoot us a mail via developers@flutterwavego.com.

Regards,
Cornelius.
