### ISSUE TITLE
Improve The Documentation

### ISSUE THREAD

**Issue by marvinhosea** [Flutterwave/Flutterwave-Rave-PHP-SDK#37]
This package documentation is not well written and needs a lot of improvement.
I do not need to state how to improve it, borrow ideas from other payments packages docs

**Comment by Corvus97** [comment]
Hello @marvinhosea ,

Thanks for raising this issue with the Team. We really appreciate the feedback.

Please note that the docs review is ongoing.

We would notify you and our developer community as soon as the docs have been reviewed.

Regards,
Cornelius

**Comment by marvinhosea** [comment]
Okay noted but I think you should close the issue after completing the issue.
